[build]
  publish = "ecstatic-thompson-9c10a6/public"
  command = "cd ecstatic-thompson-9c10a6 && hugo --minify --gc --themesDir ../.."
  
[build.environment]
  HUGO_VERSION = "0.78.1"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "/"

[[redirects]]
  from = "en/*"
  to = "en/404.html"
  status = 404

[[redirects]]
  from = "fr/*"
  to = "fr/404.html"
  status = 404