
[build]
  # command = "hugo --gc --minify -b $URL"
  command = "hugo --gc --minify $URL"
  publish = "public"

[build.environment]
  HUGO_ENV = "production"
  HUGO_VERSION = "0.78.1"
  HUGO_ENABLEGITINFO = "true"

# [context.production.environment]
#   HUGO_ENV = "production"

# [[headers]]
#   for = "*.webmanifest"
#   [headers.values]
#     Content-Type = "application/manifest+json; charset=UTF-8"

# [[headers]]
#   for = "index.xml"
#   [headers.values]
#     Content-Type = "application/rss+xml"


# [build]
#   publish = "ecstatic-thompson-9c10a6/public"
#   command = "hugo --minify --gc --themesDir ../.."
  
# [build.environment]
#   HUGO_VERSION = "0.78.1"
#   HUGO_THEME = "repo"
#   HUGO_BASEURL = "/"

[[redirects]]
  from = "en/*"
  to = "en/404.html"
  status = 404

[[redirects]]
  from = "fr/*"
  to = "fr/404.html"
  status = 404